import type { UserProfile, ActivityItem } from "../types/profile"

export const mockUserProfile: UserProfile = {
  id: "user-123",
  name: "Dr. Maria Silva",
  email: "maria.silva@universidade.edu.br",
  role: "researcher",
  institution: "Universidade Federal do Brasil",
  phone: "+55 11 99999-9999",
  bio: "Pesquisadora especializada em biodiversidade da Mata Atlântica com mais de 10 anos de experiência em coletas de campo e análises taxonômicas. Doutora em Biologia pela USP, com foco em conservação de espécies nativas.",
  avatar_url: "/placeholder.svg?height=200&width=200",
  status: "active",
  specializations: ["Botânica", "Taxonomia", "Conservação", "Ecologia"],
  orcid: "0000-0000-0000-0000",
  researchGate: "Maria_Silva123",
  linkedin: "maria-silva-bio",
  website: "https://mariasilva.bio.br",
  address: {
    street: "Rua das Flores, 123",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    zipCode: "01234-567",
  },
  preferences: {
    language: "pt-BR",
    timezone: "America/Sao_Paulo",
    emailNotifications: true,
    pushNotifications: false,
    publicProfile: true,
  },
  createdAt: "2024-01-15",
  lastLoginAt: "2024-01-22T14:30:00Z",
  projectsCount: 5,
  collectionsCount: 23,
  samplesCount: 87,
  collaborationsCount: 12,
}

export const mockRecentActivity: ActivityItem[] = [
  {
    id: "1",
    type: "collection_added",
    title: "Nova coleta registrada",
    description: "Cecropia pachystachya coletada na Trilha do Morro",
    entityId: "collection-1",
    entityType: "collection",
    timestamp: "2024-01-22T10:30:00Z",
  },
  {
    id: "2",
    type: "sample_registered",
    title: "Amostra catalogada",
    description: "Folha jovem processada - Código CP-001-F1",
    entityId: "sample-1",
    entityType: "sample",
    timestamp: "2024-01-21T16:45:00Z",
  },
  {
    id: "3",
    type: "project_created",
    title: "Projeto criado",
    description: "Flora do Cerrado - Novo projeto de catalogação",
    entityId: "project-3",
    entityType: "project",
    timestamp: "2024-01-20T09:15:00Z",
  },
  {
    id: "4",
    type: "collaboration_joined",
    title: "Colaboração iniciada",
    description: "Adicionado como colaborador no projeto Fauna Aquática",
    entityId: "project-2",
    entityType: "project",
    timestamp: "2024-01-19T14:20:00Z",
  },
]
